name: LightningLobby
version: '${project.version}'
main: lightninglobby.lightninglobby.LightningLobby
api-version: 1.16
authors: [ JTMcQuigg ]
description: Moves skript to actual plugin for minigames lobby
website: http://web.lightning-mc.xyz/
