name: LightningLobby
version: '${project.version}'
main: lightninglobby.lightninglobby.LightningLobby
api-version: 1.17
authors: [ JTMcQuigg ]
description: Moves skript to actual plugin for minigames lobby
website: http://web.lightning-mc.xyz/
commands:
  gmc:
    description: set gamemode to creative
    usage: /<command>
    aliases: [gmcreative]
  gma:
    description: set gamemode to adventure
    usage: /<command>
    aliases: [ gmadventure]
  gms:
    description: set gamemode to survival
    usage: /<command>
    aliases: [gmsurvival]
  gmsp:
    description: set gamemode to spectator
    usage: /<command>
    aliases: [gmspectator]
permissions:
  gamemode.change:
    description: allows updating gamemode